
package Recognizer;


public class InfoWindow extends javax.swing.JFrame {


    public InfoWindow(String nomeCompleto, String cargo) {
        initComponents();
        
        labelNome.setText("Nome: " + nomeCompleto);
        labelCargo.setText("Cargo: " + cargo);
        
        mostrarInformacoes(cargo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelInformacoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNome.setText("Nome:");
        jPanel1.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        labelCargo.setText("Cargo:");
        jPanel1.add(labelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        labelInformacoes.setText("Informações:");
        jPanel1.add(labelInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoWindow("Teste Nome", "Teste Cargo").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelInformacoes;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables

    private void mostrarInformacoes(String cargo) {
        StringBuilder informacoes = new StringBuilder();
        String n1 = "Informações Nível 1: Acesso geral para todos:\nAmazonia está pegando fogo!\nCuidado com as queimas e onças queimadas\n", n2 = "Informações Nível 2: Acesso restrito a diretores de divisões:\nMadeiras sendo vendidas em Cuba\nÁgua com resíduos toxicos\n\n", n3="Informações Nível 3: Acesso total aos dados estratégicos:\nReunião com o ministro do meio ambiente de Cuba\nQueimadas são Fake\n\n";
        
        switch (cargo) {
            case "Nível 3":
                informacoes.append(n3);
                informacoes.append(n2);
                informacoes.append(n1);
                break;
            case "Nível 2":
                informacoes.append(n2);
                informacoes.append(n1);
                break;
            case "Nível 1":
            default:
                informacoes.append(n1);
                break;
        }

        // Atualiza o JLabel com as informações
        labelInformacoes.setText("<html>" + informacoes.toString().replaceAll("\n", "<br/>") + "</html>");
    }

}
